name: appfw-policies
namespace: neustar.citrix.adc.stylebooks
version: "6.2"
display-name: VServer To AppFw Policy Bindings StyleBook
private: true
description: |    
    StyleBook that given a set of certificates, creates the corresponding certkeys and bind them to the given vserver.
schema-version: "1.0"
import-stylebooks:
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.0"
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "13.0"
  -
    namespace: neustar.citrix.adc.stylebooks
    prefix: neustar
    version: "6.2"
parameters:
  -
    name: customer-name
    type: string
    required: true
    pattern: "^[A-Z0-9]{2}_[A-Z0-9]{2,10}$"
  -
    name: vserver-name
    type: string
    required: true
  -
    name: policyname-list
    type: string[]

substitutions:
  waf-policyname(customername, profilename): $customername + "-" + $profilename + "-appfw-pol"
components:
  -
    name: policies-comp
    type: object
    repeat: $parameters.policyname-list
    repeat-item: policyname
    properties:
      name: $substitutions.waf-policyname($parameters.customer-name, $policyname)
      type: POLICY
      bind-point: REQUEST
  -
    name: appfw-policies-bindings-comp
    type: stlb::vserver-appfwpolicies-bindings
    properties:
        vserver-name: $parameters.vserver-name
        vserver-type: LBVSERVER
        policies: $components.policies-comp.properties
