
name: appfw-config
namespace: neustar.citrix.adc.stylebooks
version: "6.2"
display-name: AppFw Config StyleBook
description: AppFw |    
    This StyleBook contains the App Firewall Protections that can be applied to traffic by Citrix ADC
private: true
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    version: "13.0"
    prefix: ns
  - 
    namespace: com.citrix.adc.stylebooks
    version: "1.0"
    prefix: stlb
  -
    namespace: neustar.citrix.adc.stylebooks
    prefix: neustar
    version: "6.2"
parameters:
  -
    name: customer-name
    label: Customer
    description: Customer Name or ID that is used to differentiate a customer's config objects
    type: string
    required: true
    pattern: "^[A-Z0-9]{2}_[A-Z0-9]{2,10}$"

parameters-default-sources:
  - neustar::appfw-config-params
substitutions:
  profilename(name): $name + "-appfw-profile"
  waf-policyname(customername, profilename): $customername + "-" + $profilename + "-appfw-pol"
components:
  -
    name: appfw-profile-comp
    type: neustar::appfw-profile-adv
    properties:
      name: $parameters.customer-name + "-" + $parameters.profile-name
      type: $parameters.profile-type
      customer-name: $parameters.customer-name
    properties-default-sources:
      - $parameters.profile-settings
  -
    name: appfw-policy-comp
    type: ns::appfwpolicy
    description: This component creates appfw policy
    properties:
      name: $parameters.customer-name + "-" + $parameters.profile-name + "-appfw-pol"
      rule: $parameters.rule
      profilename: $parameters.customer-name + "-" + $parameters.profile-name
      # -
      #   name: appfw-iprep-policy-comp
      #   type: ns::appfwpolicy
      #   condition: $parameters.profile-settings.enable-ipreputation
      #   description: This component creates an additional appfw policy with ip-reputation.
      #   properties:
      #     name: $parameters.customer-name + "-" + $parameters.profile-name + "-iprep-pol"
      #     rule: CLIENT.IP.SRC.IPREP_IS_MALICIOUS
      #     profilename: APPFW_BLOCK
      #   components:
      #     -
      #       name: appfwpolicy-appfwpolicylabel-binding-comp
      #       type: ns::appfwpolicylabel_appfwpolicy_binding
      #       description: Binds the appfw policy created in the parent component to the request policy label
      #       properties:
      #           labelname: $parent.parent.properties.labelname
      #           policyname: $parent.properties.name
      #           gotopriorityexpression: END
      #           priority: 20
outputs:
  -
    name: appfw-policy
    value: $components.appfw-policy-comp.properties.name