name: bot-policies
namespace: neustar.citrix.adc.stylebooks
version: "6.2"
display-name: VServer To AppFw Policy Bindings StyleBook
private: true
description: |    
    StyleBook that given a set of certificates, creates the corresponding certkeys and bind them to the given vserver.
schema-version: "1.0"
import-stylebooks:
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.0"
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "13.0"
parameters:
  -
    name: customer-name
    type: string
    required: true
    pattern: "^[A-Z0-9]{2}_[A-Z0-9]{2,10}$"
  -
    name: vserver-name
    type: string
    required: true
  -
    name: policyname-list
    type: string[]

substitutions:
  bot-policyname(customername, profilename): $customername + "-" + $profilename + "-bot-pol"
  priority(ndx): 200 + ($ndx * 10)
components:
  - 
    name: lbvserver-bot-policy-binding-comp
    type: ns::lbvserver_botpolicy_binding
    description: Component for binding bot policies and lbvserver
    repeat: $parameters.policyname-list
    repeat-item: policyname
    repeat-index: ndx
    properties: 
      name: $parameters.vserver-name
      policyname: $substitutions.bot-policyname($parameters.customer-name, $policyname)
      bindpoint: REQUEST
      priority: $substitutions.priority($ndx)
      gotopriorityexpression: NEXT

