name: customer-template
namespace: neustar.citrix.adc.stylebooks
version: "6.2"
display-name: NeuStar Customer Apps StyleBooks
description: |    
    This StyleBook contains the configuration of all the apps for a customer.
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "13.0"
  -
    namespace: neustar.citrix.adc.stylebooks
    prefix: neustar
    version: "6.2"
parameters:
  - 
    name: customer-name
    label: Customer
    description: Customer Name or ID that is used to differentiate a customer's config objects
    type: string
    required: true
    pattern: "^[A-Z0-9]{2}_[A-Z0-9]{2,10}$"
    key: true
    gui:
      updatable: false
  -
    name: applications
    label: List of Applications
    type: neustar::app-template-params[]
  -
    name: shared-objects
    label: Shared config
    type: neustar::customer-shared-config-template-params
    gui:
      collapse_pane: true
substitutions:
  is-none-bool(obj): if-then-else(exists($obj), true, false)
  monitorname(appname, name): $appname + "-" + $name
  sslprofilename(customername, name): $customername + "-" + $name + "-spf" 
  sslprofilenamebk(customername, name): $customername + "-" + $name + "-spb"
  ciphergroupname(customername, name): $customername + "-" + $name + "-cgf"
  ciphergroupnamebk(customername, name): $customername + "-" + $name + "-cgb"
  listname(name): replace($parameters.customer-name + "_" + $name + "_list", "-", "_")

  state:
    true: ENABLED
    false: DISABLED
  stateyn:
    true: "YES"
    false: "NO"
components:
  -
    name: cipher-comp
    type: ns::sslcipher
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: ssl-profile
    properties:
      ciphergroupname: $substitutions.ciphergroupname($parameters.customer-name, $ssl-profile.sslprofile-name)
    components:
      -
        name: cipher-bindings
        type: ns::sslcipher_sslciphersuite_binding
        repeat: $ssl-profile.ssl-ciphers
        repeat-item: cipher
        properties:
          ciphergroupname: $parent.properties.ciphergroupname
          ciphername: $cipher
  -
    name: cipher-b-comp
    type: ns::sslcipher
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: ssl-profile-b
    properties:
      ciphergroupname: $substitutions.ciphergroupnamebk($parameters.customer-name, $ssl-profile-b.sslprofile-name) 
    components:
      -
        name: cipher-bindings
        type: ns::sslcipher_sslciphersuite_binding
        condition: $ssl-profile-b.ssl-ciphers-b
        repeat: $ssl-profile-b.ssl-ciphers-b
        #repeat-condition:  not(contains($cipher,"TLS1.3"))
        repeat-item: cipher
        properties:
          ciphergroupname: $parent.properties.ciphergroupname
          ciphername: $cipher
  - 
    name: sslprofile-f-comp
    type: ns::sslprofile
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: ssl-profile
    properties:
      name: $substitutions.sslprofilename($parameters.customer-name, $ssl-profile.sslprofile-name)
      sslprofiletype: "FrontEnd"
      sessreuse?: $substitutions.state[$ssl-profile.session-reuse]
      clientauth: $substitutions.state[$ssl-profile.client-auth]
      snihttphostmatch?: $ssl-profile.sni-http-host-match
      zerorttearlydata: $substitutions.state[$ssl-profile.zero-rtt]
      ocspstapling: $substitutions.state[$ssl-profile.ocsp-stapling]
      cipherredirect: $substitutions.state[$ssl-profile.cipher-redirect]
      cipherurl?: $ssl-profile.cipher-url
      sslredirect?: $substitutions.state[$ssl-profile.ssl-redirect]
      sesstimeout?: $ssl-profile.session-timeout
      clientauthuseboundcachain: $substitutions.state[$ssl-profile.only-bound-cas]
      ssl3?: $substitutions.state[$ssl-profile.ssl-protocols.ssl3]
      tls1?: $substitutions.state[$ssl-profile.ssl-protocols.tls1]
      tls11?: $substitutions.state[$ssl-profile.ssl-protocols.tls11]
      tls12?: $substitutions.state[$ssl-profile.ssl-protocols.tls12]
      tls13?: $substitutions.state[$ssl-profile.ssl-protocols.tls13]
      hsts?: $substitutions.state[$substitutions.is-none-bool($ssl-profile.hsts)]
      maxage?: $ssl-profile.hsts.maxage
      includesubdomains?: $substitutions.stateyn[$ssl-profile.hsts.includesubs]
      preload?: $substitutions.stateyn[$ssl-profile.hsts.preload]
      snienable?: $substitutions.state[$ssl-profile.sni]
      nodefaultbindings: "YES"
    components:
      -
        name: sslprofile-sslcipher-comp-f
        type: ns::sslprofile_sslcipher_binding
        properties:
          name: $parent.properties.name
          ciphername: $substitutions.ciphergroupname($parameters.customer-name, $ssl-profile.sslprofile-name)
      -
        name: sslprofile-ecccurve-comp-f
        type: ns::sslprofile_ecccurve_binding
        properties:
          name: $parent.properties.name
          ecccurvename: "ALL"
  -
    name: sslprofile-b-comp
    type: ns::sslprofile
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: ssl-prof
    properties:
      name: $substitutions.sslprofilenamebk($parameters.customer-name, $ssl-prof.sslprofile-name)
      sslprofiletype: "BackEnd"
      sessreuse?: $substitutions.state[$ssl-prof.session-reuse]
      sesstimeout?: $ssl-prof.session-timeout
      ssl3?: $substitutions.state[$ssl-prof.ssl-protocols.ssl3]
      tls1?: $substitutions.state[$ssl-prof.ssl-protocols.tls1]
      tls11?: $substitutions.state[$ssl-prof.ssl-protocols.tls11]
      tls12?: $substitutions.state[$ssl-prof.ssl-protocols.tls12]
      snienable?: $substitutions.state[$substitutions.is-none-bool($ssl-prof.backend-sni)]
      commonname?: if-then-else(exists($ssl-prof.backend-sni), $ssl-prof.backend-sni.common-name)
      nodefaultbindings: "YES"
    components:
        -
          name: sslprofile-sslcipher-comp-bk
          type: ns::sslprofile_sslcipher_binding 
          properties:
            name: $parent.properties.name
            ciphername: $substitutions.ciphergroupnamebk($parameters.customer-name, $ssl-prof.sslprofile-name)
        -
          name: sslprofile-ecccurve-comp-bk
          type: ns::sslprofile_ecccurve_binding
          properties:
            name: $parent.properties.name
            ecccurvename: "ALL"
  -
    name: appfw-config-comp
    type: neustar::appfw-config
    repeat: $parameters.shared-objects.waf-profiles
    repeat-item: waf-profile
    properties:
      customer-name: $parameters.customer-name
    properties-default-sources:
      - $waf-profile
  -
    name: bot-config-comp
    type: neustar::bot-policy
    repeat: $parameters.shared-objects.bot-profiles
    repeat-item: bot-profile
    properties:
      customer-name: $parameters.customer-name
    properties-default-sources:
      - $bot-profile
  -
    name: iplist-comp
    type: ns::policydataset
    repeat: $parameters.shared-objects.list-configs
    repeat-item: list
    repeat-condition: $list.list-type == "ipv4" or $list.list-type == "ipv6"
    properties:
      name: $substitutions.listname($list.name)
      type: $list.list-type
    components:
      -
        name: iplist-bindings
        type: ns::policydataset_value_binding
        repeat: $list.values
        repeat-item: val
        properties:
          name: $parent.properties.name
          value: $val
  -
    name: cclist-comp
    type: ns::policypatset
    repeat: $parameters.shared-objects.list-configs
    repeat-item: list
    repeat-condition: $list.list-type == "countryCode"
    properties:
      name: $substitutions.listname($list.name)
    components:
      -
        name: cclist-bindings
        type: ns::policypatset_pattern_binding
        repeat: $list.values
        repeat-item: val
        properties:
          name: $parent.properties.name
          String: $val
  -
    name: responder-configs-comp
    type: neustar::responder-config-params
    repeat: $parameters.shared-objects.responder-configs
    repeat-item: responder
    properties-default-sources:
      - $responder
  -
    name: ssl-profiles-comp
    type: neustar::ssl-profile-params
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: profile
    properties-default-sources:
      - $profile
  -
    name: applications-comp
    type: neustar::app-template
    repeat: $parameters.applications
    repeat-item: application
    properties-default-sources:
      - $application
    properties:
      customer-name: $parameters.customer-name
      shared-app-configs:
        responder-configs: $components.responder-configs-comp.properties
        ssl-profiles: $components.ssl-profiles-comp.properties



