name: customer-shared-config-template-params
namespace: neustar.citrix.adc.stylebooks
version: "6.2"
display-name: Neustar Shared Config Objects StyleBook
description: |    
    This StyleBook contains the configuration elements that can be shared by multiple apps.
schema-version: "1.0"
private: true
import-stylebooks: 
  -
    namespace: neustar.citrix.adc.stylebooks
    prefix: neustar
    version: "6.2"
  -
    namespace: neustar.citrix.adc.commontypes
    prefix: cmtypes
    version: "6.2"
parameters:
  # - 
  #   name: certificates
  #   label: "List of Certificates"
  #   description: "Certificates for this virtual server if this load Balanced application is exposed using SSL"
  #   type: neustar::certificate-params[]
  -
    name: ssl-profiles
    label: List of SSL Profiles
    type: object[]
    parameters-default-sources:
      - neustar::ssl-profile-params
  - 
    name: waf-profiles
    label: List of WAF Profiles
    description: Configure WAF Profiles
    type: object[]
    parameters-default-sources:
      - neustar::appfw-config-params
  - 
    name: bot-profiles
    label: List of Bot Profiles
    description: Configure Bot Profiles
    type: object[]
    parameters-default-sources:
      - cmtypes::bot-policy-params
  -
    name: responder-configs
    label: Responder Configs Section
    type: object[]
    gui: 
        collapse_pane: true  
    parameters-default-sources:
      - neustar::responder-config-params
  -
    name: list-configs
    label: IP and Country Lists
    type: object[]
    gui: 
        collapse_pane: true  
    parameters-default-sources:
      - neustar::arb-list-params