name: responder-config-params
namespace: neustar.citrix.adc.stylebooks 
version: "6.2"
display-name: "StyleBook contains the parameters of an Responder config"
description: "StyleBook contains the settings of an Responder config"
schema-version: "1.0"
private: true
parameters:
    -
      name: name
      type: string
      label: Name
      description: Name
      required: true
    - 
      name: rate-limiter
      type: object
      label: Rate Limiting
      description: Rate Limiting
      parameters:
        -
          name: rl-field
          type: string[]
          label: Rate limit field expression
          description: Rate limit field expression
          required: true
        -
          name: rl-count
          type: number
          label: Count
          description: Count
          required: true
        - 
          name: rl-time
          type: number
          label: Per ? Seconds
          default: 5
          allowed-values:
            - 1
            - 5
            - 10
            - 30
            - 60
            - 300
    -
      name: action
      type: string
      label: Action
      description: Select an action to perform if expression matches
      required: true
      allowed-values:
        - no_action
        - log
        - block
        - redirect_to
        - respond_with
    -
      name: expression
      type: string
      label: Rule
      description: The netscaler specific syntax rule(s) to match.  Multiple rules can be combined with && or ||.  List names from country/ip lists are referenced here by customer + _ + listname + _list.  Example - CLIENT.IP.SRC.TYPECAST_TEXT_T.EQUALS_ANY("SP_CUSTOMER_myfirstlist_list") or CLIENT.IP.SRC.LOCATION.GET(1).SET_TEXT_MODE(ignorecase).EQUALS_ANY("SP_CUSTOMER_mycountrylist_list")
    -
      name: target
      type: string
      label: Target
      description: Not used for log and block.  For redirect, enter a URL.  For respond, enter a response body 
