---
name: shared-configs-for-apps-params
namespace: neustar.citrix.adc.stylebooks 
version: "6.2"
display-name: "StyleBook contains the parameters of Shared configs exposed to Apps"
description: "StyleBook contains the parameters of Shared configs exposed to Apps"
schema-version: "1.0"
private: true
import-stylebooks:
  - 
    namespace: com.citrix.adc.commontypes
    prefix: cmtypes
    version: "1.0"
  - 
    namespace: neustar.citrix.adc.commontypes
    prefix: neustar
    version: "6.2"
parameters:
  -
    name: shared-app-configs
    type: object
    parameters:
      -
        name: responder-configs
        type: object[]
        parameters:
          -
            name: name
            type: string
            required: true
          - 
            name: rate-limiter
            type: object
            parameters:
            -
              name: rl-field
              type: string[]
            -
              name: rl-count
              type: number
            - 
              name: rl-time
              type: number
          -
            name: action
            type: string
          -
            name: expression
            type: string
          -
            name: target
            type: string
      -
        name: ssl-profiles
        type: object[]
        parameters:
          -
            name: sslprofile-name
            type: string

          -
            name: ssl-protocols
            type: object
            parameters:
              -
                name: ssl3
                type: boolean
              -
                name: tls1
                type: boolean
              -
                name: tls11
                type: boolean
              -
                name: tls12
                type: boolean
              -
                name: tls13
                type: boolean
          - 
            name: hsts
            type: object
            parameters:
              - 
                name: maxage
                type: number
              -
                name: preload
                type: boolean
              -
                name: includesubs
                type: boolean
          -
            name: sni
            type: boolean
          -
            name: backend-sni
            type: object
            parameters:
              - 
                name: common-name
                type: string
          -
            name: ssl-ciphers
            type: string[]
          -
            name: ssl-ciphers-b
            type: string[]
          -
            name: backend-ciphers
            type: boolean
          -
            name: zero-rtt
            type: boolean
          -
            name: sni-http-host-match
            type: string
          - 
            name: ocsp-stapling
            type: boolean
          -
            name: client-auth
            type: boolean
          -
            name: cipher-redirect
            type: boolean
          -
            name: cipher-url
            type: string
          - 
            name: ssl-redirect
            type: boolean
          -
            name: session-reuse
            type: boolean
          -
            name: session-timeout
            type: number
          -
            name: only-bound-cas
            type: boolean



